title: Hola!!
author: Hasibul Islam
email: star.sazzad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog in GitHub pages
theme: minima


# social links
twitter_username: starhasibul # DO NOT include the @ character, or else the build will fail!
github_username:  starhasibul # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
